version: "3.9"  # optional since v1.27.0
services:
  web_api:
    build:
      context: .
      dockerfile: ./
    image: prueba-afp
    container_name: contenedor-prueba-afp
    ports:
      - "5000:8081"


  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name:  afp-contenedor-sql
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=<Aramos2020$>